### ISSUE TITLE
Do you really need `numpy==1.15.4`?

### ISSUE THREAD

**Issue by asodeur** [crossbario/zlmdb#20]
* ZLMDB version: >=19,2,2
* Python version: *
* Operating System: *

The requirement `numpy==1.15.4` seems a little narrow. Could this potentially be relaxed?

**Comment by oberstet** [comment]
> The requirement numpy==1.15.4 seems a little narrow. Could this potentially be relaxed?

yes, I agree, this is quite narrow and not sth we usually do (pin a dependency down to the point version). the practical reason was, that we had been fighting with other dependencies (depending on numpy), which only worked with this specific version. I forgot what exactly.

so on the one hand I agree, on the other hand, practically, we won't change it short term .. sorry. But I leave this issue open, so that we can come back later

also, if this is actually about crossbar.io: shouldn't be a problem when following what we recommend: install crossbar.io into a dedicated virtualenv.

should this be about numpy on windows: "no problem" on that as well .. we build crossbar.io, or more precisely, our commercially extended version crossbarfx on that platform as part of our CI, eg here is the single-file EXE for windows: https://download.crossbario.com/crossbarfx/windows-amd64/crossbarfx-latest.exe


![Bildschirmfoto von 2020-02-27 16-38-43](https://user-images.githubusercontent.com/233340/75462209-30f2e000-5984-11ea-88ee-5e425955364e.png)
![Bildschirmfoto von 2020-02-27 16-38-25](https://user-images.githubusercontent.com/233340/75462211-318b7680-5984-11ea-8283-f0805964c36d.png)

**Comment by strichter** [comment]
We have found that for other reasons numpy 1.15.4 does not work properly with Python 3.8. We are now forcing our build to use numpy 1.18.2, but we have to manually adjust our requirements file after auto-generation due to this stiff requirement.

**Comment by oberstet** [comment]
> We have found that for other reasons numpy 1.15.4 does not work properly with Python 3.8.

mmh, ok. anything you found specificially that doesn't work on py 3.8?

we do test on py 3.8 (here and for other of our stuff):

https://travis-ci.com/github/crossbario/zlmdb

**Comment by kedder** [comment]
Running corssbar.io in a dedicated virtualenv is not an option for us and we can't upgrade numpy because of this restriction. Now, the option is to fork zlmdb and relax the requirement, but it is not clear what is going to be broken by that.

Is this numpy requirement has something to do with how zlmdb uses numpy, or it is something not related to zlmdb or crossbar itself?

**Comment by kedder** [comment]
And zlmdb doesn't even seem to be used by https://github.com/crossbario/crossbar. It is merely declared as dependency. Would it make sense to remove it from crossbar dependencies?

**Comment by oberstet** [comment]
fwiw, I'm looking into upgrading to NumPy 1.19.4

current status:

* our travis ci currently is using PyPy 7.1.1-beta0 with GCC 6.2.0 20160901
* this runs into Py_RETURN_NOTIMPLEMENTED undeclared https://travis-ci.com/github/crossbario/zlmdb/jobs/440461345
PyPy 7.2.0 for NumPy 1.19.4
* this was fixed in PyPy 7.2.0 https://doc.pypy.org/en/latest/release-v7.2.0.html#python-3-6-c-api

**Comment by strichter** [comment]
Could we simply not pin numpy at all or at least give it greater equal? No complex application will ever resolve with a single version pinned dependency.

**Comment by spomjaksilp** [comment]
We are also running into this issue regularly. It got even more inconvenient since the 20.3 version of `pip` which does not let one install incompatible versions via `force`. So, right now we would have to downgrade `pip` to force `numpy 1.19` to use crossbar in our setup ...

**Comment by oberstet** [comment]
ok, I'm gonna give it a new try:

```
-    'numpy==1.19.4',
+    'numpy>=1.19.4',
```

> note: we do have deps and will do a bunch of tests to see if all works with 1.19.4 - if so, we'll continue with ^ .. I hope it works. if stuff breaks, we'll have to see ..

----

fwiw:

> No complex application will ever resolve with a single version pinned dependency.

yes, but there is no need to install 2 apps into 1 venv. in general, IMO, mixing deps across apps in a bad idea. any dep other than the C runtime and syscall ABI. when using OS containers, that's the case anyways. when installing on host, one venv per app achieves a poor mans version of that.

**Comment by spomjaksilp** [comment]
> ok, I'm gonna give it a new try:
> 
> ```
> -    'numpy==1.19.4',
> +    'numpy>=1.19.4',
> ```

I just found out I am an idiot ... I did look at the pypi version which is release 20.8.1
this repo's upstream works perfectly, thx!

**Comment by oberstet** [comment]
released in:

* https://github.com/crossbario/zlmdb/tree/v20.12.1
* https://pypi.org/project/zlmdb/20.12.1/

**Comment by strichter** [comment]
Thanks, much appreciated.
